In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('../Data/transactions.csv')

df.head()

   customer_id tr_datetime  mcc_code  tr_type    amount term_id
0     39026145  0 10:23:26      4814     1030  -2245.92     NaN
1     39026145  1 10:19:29      6011     7010  56147.89     NaN
2     39026145  1 10:20:56      4829     2330 -56147.89     NaN
3     39026145  1 10:39:54      5499     1010  -1392.47     NaN
4     39026145  2 15:33:42      5499     1010   -920.83     NaN

In [8]:
new_df = df.groupby('customer_id').count().sort_values(by = 'tr_datetime', ascending=False)

new_df = new_df[new_df.tr_datetime>999]

new_df.index

Index([70780820, 45479973, 90796706,  6736634, 60151282, 35071735,  7999570,
       63233186, 25270793, 11701078,
       ...
       94756196, 79234235,  2470443, 42224807, 34767686, 24644305, 10011328,
       48101409, 68526161, 86397318],
      dtype='int64', name='customer_id', length=969)

In [9]:
df[df.customer_id.isin(new_df.index)]

         customer_id   tr_datetime  mcc_code  tr_type    amount   term_id
0           39026145    0 10:23:26      4814     1030  -2245.92       NaN
1           39026145    1 10:19:29      6011     7010  56147.89       NaN
2           39026145    1 10:20:56      4829     2330 -56147.89       NaN
3           39026145    1 10:39:54      5499     1010  -1392.47       NaN
4           39026145    2 15:33:42      5499     1010   -920.83       NaN
...              ...           ...       ...      ...       ...       ...
6811235     79686538  456 13:57:12      4814     1030  -4771.90    888908
6811236     79686538  456 18:04:00      6010     7031     22.46  10777890
6811237     79686538  456 19:07:10      4814     1030  -2268.37    888913
6811238     79686538  456 19:13:24      4814     1030  -1122.96    888906
6811239     79686538  456 21:29:51      6010     7071  22459.16    888986

[1954933 rows x 6 columns]

In [10]:
df[df.customer_id.isin(new_df.index)].to_csv ('transactions_short.csv')

df.customer_id

0          39026145
1          39026145
2          39026145
3          39026145
4          39026145
             ...
6849341    61870738
6849342    61870738
6849343    61870738
6849344    61870738
6849345    61870738
Name: customer_id, Length: 6849346, dtype: int64

## Задание 1

1. Для столбца tr_type датафрейма transactions выберите произвольные 1000 строк с помощью метода sample
2. В полученной на предыдущем этапе подвыборке найдите долю транзакций (стобец tr_description в датасете tr_types), в которой содержится подстрока 'POS' или 'ATM'

In [13]:
tr_types = pd.read_csv('../Data/tr_types.csv', sep=';')

tr_types

     tr_type                                     tr_description
0       3200  Плата за предоставление услуг посредством моби...
1       3210  Плата за предоставление отчета по счету карты ...
2       3800  Плата за обслуживание банковской карты (за пер...
3       4000            Плата за получение наличных в Сбербанке
4       4001  Плата за получение наличных в Сбербанке (в дру...
..       ...                                                ...
150     2990                             Списание по требованию
151     2992  Списание средств для погашения задолженности п...
152     3001            Комиссия за обслуживание ссудного счета
153     3030  Плата за обслуживание банковской карты (за пос...
154     3120                Плата за досрочный перевыпуск карты

[155 rows x 2 columns]

In [16]:
sample_df = df.sample(n=1000, random_state=42)
sample_df

         customer_id   tr_datetime  mcc_code  tr_type    amount   term_id
3329768     34746864  292 15:44:57      4829     2371 -22459.16    888986
78674       66388543  277 17:19:10      5912     1110  -4735.29  77082506
1143450     49667378  414 19:22:49      5331     1010  -1515.99    854993
5114679     33073311   23 10:56:17      4814     1030  -4491.83       NaN
1362557     42399340  384 00:00:00      4789     1210 -59648.83  QE002339
...              ...           ...       ...      ...       ...       ...
1225527     91977655  211 17:37:12      4814     1030  -2245.92    888996
3734820     82356324   93 14:12:37      5691     1010 -67310.10       NaN
5864657     46055066   82 19:15:26      5541     1110  -4486.22       NaN
2888155     99195512  371 00:00:00      5311     1110  -7398.05     32026
43243       94899216   23 17:16:47      4814     1030  -6737.75       NaN

[1000 rows x 6 columns]

In [17]:
type_dict = dict(zip(tr_types['tr_type'], tr_types['tr_description']))

sample_df['tr_description'] = sample_df['tr_type'].map(type_dict)

mask = sample_df['tr_description'].str.contains('POS|ATM', case=False, na=False)
fraction = mask.mean()

print(f"Доля транзакций с POS/ATM: {fraction:.4f}")

Доля транзакций с POS/ATM: 0.3760

## Задание 2

1. Для столбца tr_type датафрейма transactions посчитайте частоту встречаемости всех типов транзакций tr_type в transactions.
2. Выведите топ-10 транзакций по частоте встречаемости (вывести для них tr_description тоже).

In [20]:
type_freq = df['tr_type'].value_counts().reset_index()
type_freq.columns = ['tr_type', 'frequency']

print("Частота встречаемости всех типов транзакций:")
print(type_freq)

Частота встречаемости всех типов транзакций:
    tr_type  frequency
0      1010    1589734
1      2010    1040713
2      1030     970994
3      1110     928154
4      7070     691896
..      ...        ...
72     8146         10
73     4045          8
74     4035          3
75     7044          1
76     2000          1

[77 rows x 2 columns]

In [21]:
top10_types = type_freq.head(10).copy()
top10_types['tr_description'] = top10_types['tr_type'].map(type_dict)

print(top10_types)

   tr_type  frequency                                     tr_description
0     1010    1589734                              Покупка. POS ТУ СБ РФ
1     2010    1040713              Выдача наличных в АТМ Сбербанк России
2     1030     970994                     Оплата услуги. Банкоматы СБ РФ
3     1110     928154                             Покупка. POS ТУ Россия
4     7070     691896  Перевод на карту (с карты) через Мобильный бан...
5     2370     376521  Списание с карты на карту по операции <перевод...
6     7010     258088       Взнос наличных через АТМ (в своем тер.банке)
7     7030     155200  Перевод на карту (с карты) через АТМ (в предел...
8     1100     117870                                Покупка. ТУ  Россия
9     7071      96146  Перевод на карту (с карты) через Мобильный бан...

## Задание 3

1. В датафрейме transactions найдите клиента с максимальной суммой приходов на карту
2. В датафрейме transactions найдите клиента с максимальной суммой расходов по карте
3. Найдите модуль разницы для этих клиентов между суммой расходов и суммой приходов

In [25]:
income_df = df[df['amount'] > 0]
customer_income = income_df.groupby('customer_id')['amount'].sum()
max_income_customer = customer_income.idxmax()
max_income_sum = customer_income.max()

print(f"Клиент с максимальной суммой приходов: {max_income_customer}, сумма: {max_income_sum:.2f}")

Клиент с максимальной суммой приходов: 48281795, сумма: 8542244401.49

In [26]:
expense_df = df[df['amount'] < 0]
customer_expense = expense_df.groupby('customer_id')['amount'].sum().abs()
max_expense_customer = customer_expense.idxmax()
max_expense_sum = customer_expense.max()

print(f"Клиент с максимальной суммой расходов: {max_expense_customer}, сумма: {max_expense_sum:.2f}")

Клиент с максимальной суммой расходов: 48281795, сумма: 8541879253.05

In [30]:
income_customer_income = df[(df['customer_id'] == max_income_customer) & (df['amount'] > 0)]['amount'].sum()
income_customer_expense = df[(df['customer_id'] == max_income_customer) & (df['amount'] < 0)]['amount'].sum()
diff_for_income_customer = abs(income_customer_expense - income_customer_income)

print(f"Модуль разницы (расходы - приходы) для клиента с максимальной суммой приходов {max_expense_customer}: {diff_for_income_customer:.2f}")

Модуль разницы (расходы - приходы) для клиента с максимальной суммой приходов 48281795: 17084123654.54

In [29]:
expense_customer_income = df[(df['customer_id'] == max_expense_customer) & (df['amount'] > 0)]['amount'].sum()
expense_customer_expense = df[(df['customer_id'] == max_expense_customer) & (df['amount'] < 0)]['amount'].sum()
diff_for_expense_customer = abs(expense_customer_expense - expense_customer_income)

print(f"Модуль разницы (расходы - приходы) для клиента с максимальной суммой расходов {max_expense_customer}: {diff_for_expense_customer:.2f}")

Модуль разницы (расходы - приходы) для клиента с максимальной суммой расходов 48281795: 17084123654.54

Получилось одинаково, т.к. клиент с максимальной суммой расходов и приходов один и тот же

## Задание 4
1. Найдите среднее арифметическое и медиану по amount по всем типам транзакций из топ 10 из задания 2
2. Найдите среднее арифметическое и медиану по amount по всем типам транзакций для клиентов из задания 3

In [32]:
top10_types_list = top10_types['tr_type'].tolist()
top10_transactions = df[df['tr_type'].isin(top10_types_list)]

mean_top10 = top10_transactions['amount'].mean()
median_top10 = top10_transactions['amount'].median()

print("Для топ-10 типов транзакций ")
print(f"Среднее арифметическое amount: {mean_top10:.2f}")
print(f"Медиана amount: {median_top10:.2f}")

Для топ-10 типов транзакций
Среднее арифметическое amount: -16959.58
Медиана amount: -5311.59

In [33]:
customers_list = [max_income_customer, max_expense_customer]
customers_transactions = df[df['customer_id'].isin(customers_list)]

mean_customers = customers_transactions['amount'].mean()
median_customers = customers_transactions['amount'].median()

print("Для клиентов с max приходов и max расходов")
print(f"Среднее арифметическое amount: {mean_customers:.2f}")
print(f"Медиана amount: {median_customers:.2f}")

Для клиентов с max приходов и max расходов
Среднее арифметическое amount: 231.55
Медиана amount: -4491831.54

In [49]:
transactions = pd.read_csv('../Data/transactions.csv', nrows=1000000)
gender_train = pd.read_csv('../Data/gender_train.csv')
tr_mcc_codes = pd.read_csv('../Data/tr_mcc_codes.csv', sep=';')
tr_types = pd.read_csv('../Data/tr_types.csv', sep=';')

In [50]:
tr_mcc_codes = tr_mcc_codes.drop_duplicates(subset=['mcc_code'])
tr_types = tr_types.drop_duplicates(subset=['tr_type'])

In [51]:
transactions = pd.merge(transactions, gender_train, how='left')
transactions = pd.merge(transactions, tr_mcc_codes, how='inner')
transactions = pd.merge(transactions, tr_types, how='inner')
transactions.shape

(999584, 9)

## Задание 5
1. Определите модуль разницы между средними тратами женщин и мужчин (трата - отрицательное значение amount).
2. Определите модуль разницы между средними поступлениями у мужчин и женщин

In [55]:
expenses = transactions[transactions['amount'] < 0].copy()
expenses['expense_amount'] = expenses['amount'].abs()

avg_expense_by_gender = expenses.groupby('gender')['expense_amount'].mean()
print(f"Средние траты: {avg_expense_by_gender}")

diff_expenses = abs(avg_expense_by_gender.iloc[0] - avg_expense_by_gender.iloc[1])
print(f"Модуль разницы средних трат: {diff_expenses:.2f}")

Средние траты: gender
0.0    53376.917122
1.0    86094.972042
Name: expense_amount, dtype: float64
Модуль разницы средних трат: 32718.05

In [58]:
incomes  = transactions[transactions['amount'] > 0].copy()
incomes ['incomes_amount'] = expenses['amount'].abs()

avg_income_by_gender = incomes.groupby('gender')['amount'].mean()
print(f"Средние траты: {avg_income_by_gender}")

diff_incomes = abs(avg_income_by_gender.iloc[0] - avg_income_by_gender.iloc[1])
print(f"Модуль разницы средних поступлений: {diff_incomes:.2f}")

Средние траты: gender
0.0    140984.005058
1.0     77617.434010
Name: amount, dtype: float64
Модуль разницы средних поступлений: 63366.57

## Задание 6
1. По всем типам транзакций рассчитайте максимальную сумму прихода на карту (из строго положительных сумм по столбцу amount) отдельно для мужчин и женщин (назовите ее "max_income"). Оставьте по 10 типов транзакций для мужчин и для женщин, наименьших среди всех типов транзакций по полученным значениям "max_income".
2. Выделите среди них те типы транзакций, которые встречаются одновременно и у мужчин, и у женщин

In [59]:
max_income_by_gender_type = incomes.groupby(['gender', 'tr_type'])['amount'].max().reset_index()
max_income_by_gender_type.columns = ['gender', 'tr_type', 'max_income']

men_max_income = max_income_by_gender_type[max_income_by_gender_type['gender'] == 1].nsmallest(10, 'max_income')
women_max_income = max_income_by_gender_type[max_income_by_gender_type['gender'] == 0].nsmallest(10, 'max_income')

print("Топ-10 типов транзакций с наименьшим max_income для мужчин:")
print(men_max_income[['tr_type', 'max_income']])
print("\nТоп-10 типов транзакций с наименьшим max_income для женщин:")
print(women_max_income[['tr_type', 'max_income']])

Топ-10 типов транзакций с наименьшим max_income для мужчин:
    tr_type  max_income
44     2020     2245.92
47     4110     2245.92
38     1010    28803.87
71     8100    64682.37
48     6000    79280.83
66     7041    87590.72
43     2010    89836.63
45     2110   112295.79
46     2370   113194.15
57     7015   121279.45

Топ-10 типов транзакций с наименьшим max_income для женщин:
    tr_type  max_income
10     4051     1122.96
12     4110     2245.92
13     4210     2245.92
9      2370     2335.75
11     4100     5041.86
36     7075     6737.75
6      2110    22459.16
0      1010    24839.83
5      2010    44918.32
7      2210    68315.82

## Задание 8
1. Из поля tr_datetime выделите час tr_hour, в который произошла транзакция, как первые 2 цифры до ":". (**)
2. Посчитайте количество транзакций с amount<0 в ночное время для мужчин и женщин. Ночное время - это примерно 00-06 часов.

In [60]:
transactions['tr_hour'] = transactions['tr_datetime'].str.split().str[1].str.split(':').str[0].astype(int)
print(transactions[['tr_datetime', 'tr_hour']].head())

  tr_datetime  tr_hour
0  0 10:23:26       10
1  1 10:19:29       10
2  1 10:20:56       10
3  1 10:39:54       10
4  2 15:33:42       15

In [61]:
night_transactions = transactions[(transactions['amount'] < 0) & (transactions['tr_hour'].between(0, 6))]

night_count_by_gender = night_transactions.groupby('gender').size()

print(f"Количество ночных трат (00-06) для женщин (gender=0): {night_count_by_gender.get(0, 0)}")
print(f"Количество ночных трат (00-06) для мужчин (gender=1): {night_count_by_gender.get(1, 0)}")
print(f"Всего ночных трат: {night_count_by_gender.sum()}")

Количество ночных трат (00-06) для женщин (gender=0): 43510
Количество ночных трат (00-06) для мужчин (gender=1): 46694
Всего ночных трат: 90204